import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import { GoogleGenAI } from '@google/genai';

dotenv.config();

const app = express();
const port = process.env.PORT || 3001;

app.use(cors());
app.use(express.json());

// Initialize Google Gen AI
const ai = new GoogleGenAI({ apiKey: process.env.VITE_GEMINI_API_KEY }); // Note: We read the same variable name just to not break existing env configs, though arguably should just be GEMINI_API_KEY on the backend context.

// Mock list of initially available remote songs
const songs = [
    {
        id: 1001,
        title: "Dreamscape Awakening",
        artist: "Neon Horizons",
        url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3"
    },
    {
        id: 1002,
        title: "Midnight Cruiser",
        artist: "The Synth Royals",
        url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3"
    }
];

app.get('/api/songs', (req, res) => {
    res.json(songs);
});

app.post('/api/cover', async (req, res) => {
    const { title, artist } = req.body;

    if (!title || !artist) {
        return res.status(400).json({ error: 'Title and Artist are required' });
    }

    try {
        const response = await ai.models.generateImages({
            model: 'gemini-2.5-flash-image',
            prompt: `Create an exclusive, high-quality, conceptual album cover art for the song "${title}" by "${artist}". Do not include any text, words, or typography in the image. The image should capture the abstract artistic vibe and mood of the artist and song.`,
            config: {
                numberOfImages: 1,
                aspectRatio: '1:1',
                outputMimeType: 'image/jpeg'
            }
        });

        const imageBytes = response.generatedImages?.[0]?.image?.imageBytes;
        if (!imageBytes) {
            throw new Error('No image generated by the AI.');
        }

        const dynamicUrl = `data:image/jpeg;base64,${imageBytes}`;
        res.json({ coverUrl: dynamicUrl });

    } catch (error) {
        console.error('Error generating AI Cover:', error);
        res.status(500).json({ error: 'Failed to generate album cover' });
    }
});

app.listen(port, () => {
    console.log(`Server is running on port ${port}`);
});
