import type { VercelRequest, VercelResponse } from '@vercel/node';
import { GoogleGenAI } from '@google/genai';

export default async function handler(req: VercelRequest, res: VercelResponse) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { title, artist } = req.body;

  if (!title || !artist) {
    return res.status(400).json({ error: 'Title and Artist are required' });
  }

  const apiKey = process.env.VITE_GEMINI_API_KEY || process.env.GEMINI_API_KEY;
  if (!apiKey) {
    return res.status(500).json({ error: 'API key not configured' });
  }

  try {
    const ai = new GoogleGenAI({ apiKey });
    const response = await ai.models.generateImages({
      model: 'gemini-2.5-flash-image',
      prompt: `Create an exclusive, high-quality, conceptual album cover art for the song "${title}" by "${artist}". Do not include any text, words, or typography in the image. The image should capture the abstract artistic vibe and mood of the artist and song.`,
      config: {
        numberOfImages: 1,
        aspectRatio: '1:1',
        outputMimeType: 'image/jpeg',
      },
    });

    const imageBytes = response.generatedImages?.[0]?.image?.imageBytes;
    if (!imageBytes) {
      throw new Error('No image generated by the AI.');
    }

    const dynamicUrl = `data:image/jpeg;base64,${imageBytes}`;
    return res.json({ coverUrl: dynamicUrl });
  } catch (error) {
    console.error('Error generating AI Cover:', error);
    return res.status(500).json({ error: 'Failed to generate album cover' });
  }
}
